Add better buttons
unfoldingWord/uw-editor pull request #15
Opened 2022-10-28 21:29 UTC by superdav42

I think it's an improvement 
![image](https://user-images.githubusercontent.com/1534605/198735941-d64028b1-9a96-485b-af62-24eb856d92d1.png)

2022-10-29 11:36 UTC, mandolyte commented on src/components/Buttons.jsx
> +  Redo, Save
@superdav42 could add tool tips on these. Some are more international than others. At some point, we should consider some localizations on the tool tips, but that can wait.

2022-10-29 11:37 UTC, mandolyte commented on src/components/Buttons.jsx
> +  Redo, Save
The save button does not indicate when there are saves pending. Could be probably be tied to the length of the history?

2022-10-29 11:41 UTC, mandolyte requested changes
You are right - these buttons look **much** nicer. Two things in the comments:
- provide tool tips
- make the state change of the save button reflect whether any changes have not been saved. I think this might easily be done by using the length of the undo history stack?

2022-10-31 19:46 UTC, superdav42 commented
> make the state change of the save button reflect whether any changes have not been saved. I think this might easily be done by using the length of the undo history stack?

Yep it was pretty easy. Please check it out.

2022-11-01 11:27 UTC, merged